# Generated by Django 2.2.12 on 2021-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210219_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingbid',
            field=models.IntegerField(verbose_name=8),
        ),
    ]
