# Generated by Django 2.2.12 on 2021-03-06 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210306_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='auctionItems', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
