# Generated by Django 2.2.12 on 2021-03-06 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='actualbid',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
