# Generated by Django 2.2.12 on 2021-03-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210308_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='number_of_bids',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='time_ending',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='time_starting',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
    ]
