# Generated by Django 2.2.12 on 2021-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210308_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='actualbid',
            field=models.IntegerField(null=True),
        ),
    ]
